### ISSUE TITLE
GraficoInfo não aceitando HTML e menor que 100%

### ISSUE THREAD

**Issue by gabriellearruda** [ImpulsoGov/design-system#68]
### - GraficoInfo não aceitando HTML 
Variavel Fonte não esta aceitando HTML o que não permite que consiga colocar referências e negrito, como no modelo do IP atual.
![image](https://github.com/ImpulsoGov/design-system/assets/41838989/48669906-f63d-48e7-af2b-d94068998db2)
![image](https://github.com/ImpulsoGov/design-system/assets/41838989/819fefb7-3684-4900-906f-b0262d9da262)

### - Menor que 100%
A fonte do GraficoInfo não está indo até 100% o que atrapalha a visualização do texto e deixa grande parte em branco, conforme imagem. Solicito modificação.
![image - 2023-06-29T141145 303](https://github.com/ImpulsoGov/design-system/assets/41838989/e2756b81-23e9-4eec-96b8-237a1f7df197)

**Comment by tainnaps** [comment]
Corrigido em https://github.com/ImpulsoGov/design-system/pull/70
